server:
  port: 80
spring:
  thymeleaf:
    #    view-names: thymeleaf/* ## thymeleaf ? ???? view ? ??
    prefix: classpath:/templates/
    suffix: .jsp
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  #  pattern:
  #    console: "%highlight(## %d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} %M{5}) - %msg %n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.web.servlet.DispatcherServlet: OFF
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF

    jdbc: OFF                  ### log4jdbc ?? ?? ###
    jdbc.connection: OFF       ### ??? open close ???? ??? ???. ###
    jdbc.sqlonly: OFF          ### SQL??? ??? ???, PreparedStatement? ?? ??? argument ??? ??? SQL?? ????. ###
    jdbc.sqltiming: DEBUG      ### SQL?? ?? SQL? ?????? ??? ?? ??(milliseconds)? ????. ###
    jdbc.audit: OFF            ### ResultSet? ??? ?? JDBC ?? ??? ??? ???. ?? ?? ??? ????? ??? JDBC ??? ???? ? ??? ?? ??? ????? ??? ???? ???. ###
    jdbc.resultset: OFF        ### ResultSet? ??? ?? JDBC ?? ??? ??? ???? ?? ??? ?? ??? ????. ###
    jdbc.resultsettable: DEBUG ### SQL ?? ??? ???? table? ??? ???. ###



servlet:
  encoding:
    charset: UTF-8
    enabled: true